#pragma once

#include <wrbase.h>


#ifndef __cplusplus
typedef enum DWRITE_FACTORY_TYPE {
    DWRITE_FACTORY_TYPE_SHARED,
    DWRITE_FACTORY_TYPE_ISOLATED
} DWRITE_FACTORY_TYPE;

typedef enum DWRITE_FONT_WEIGHT {
    DWRITE_FONT_WEIGHT_THIN        = 100,
    DWRITE_FONT_WEIGHT_EXTRA_LIGHT = 200,
    DWRITE_FONT_WEIGHT_ULTRA_LIGHT = 200,
    DWRITE_FONT_WEIGHT_LIGHT       = 300,
    DWRITE_FONT_WEIGHT_SEMI_LIGHT  = 350,
    DWRITE_FONT_WEIGHT_NORMAL      = 400,
    DWRITE_FONT_WEIGHT_REGULAR     = 400,
    DWRITE_FONT_WEIGHT_MEDIUM      = 500,
    DWRITE_FONT_WEIGHT_DEMI_BOLD   = 600,
    DWRITE_FONT_WEIGHT_SEMI_BOLD   = 600,
    DWRITE_FONT_WEIGHT_BOLD        = 700,
    DWRITE_FONT_WEIGHT_EXTRA_BOLD  = 800,
    DWRITE_FONT_WEIGHT_ULTRA_BOLD  = 800,
    DWRITE_FONT_WEIGHT_BLACK       = 900,
    DWRITE_FONT_WEIGHT_HEAVY       = 900,
    DWRITE_FONT_WEIGHT_EXTRA_BLACK = 950,
    DWRITE_FONT_WEIGHT_ULTRA_BLACK = 950
} DWRITE_FONT_WEIGHT;

typedef enum DWRITE_FONT_STRETCH {
    DWRITE_FONT_STRETCH_UNDEFINED       = 0,
    DWRITE_FONT_STRETCH_ULTRA_CONDENSED = 1,
    DWRITE_FONT_STRETCH_EXTRA_CONDENSED = 2,
    DWRITE_FONT_STRETCH_CONDENSED       = 3,
    DWRITE_FONT_STRETCH_SEMI_CONDENSED  = 4,
    DWRITE_FONT_STRETCH_NORMAL          = 5,
    DWRITE_FONT_STRETCH_MEDIUM          = 5,
    DWRITE_FONT_STRETCH_SEMI_EXPANDED   = 6,
    DWRITE_FONT_STRETCH_EXPANDED        = 7,
    DWRITE_FONT_STRETCH_EXTRA_EXPANDED  = 8,
    DWRITE_FONT_STRETCH_ULTRA_EXPANDED  = 9
} DWRITE_FONT_STRETCH;

typedef enum DWRITE_FONT_STYLE {
    DWRITE_FONT_STYLE_NORMAL,
    DWRITE_FONT_STYLE_OBLIQUE,
    DWRITE_FONT_STYLE_ITALIC
} DWRITE_FONT_STYLE;

typedef struct IDWriteFactory        IDWriteFactory;
typedef struct IDWriteFontCollection IDWriteFontCollection;
typedef struct IDWriteTextFormat     IDWriteTextFormat;
#endif


_WR_EXTERN_C_ HRESULT WINAPI WrDWrite_Factory_Create(DWRITE_FACTORY_TYPE eType, IDWriteFactory **ptrpFactory);
_WR_EXTERN_C_ HRESULT WINAPI WrDWrite_Factory_CreateTextFormat(IDWriteFactory *sFactory, WCHAR const *wstrFontFamilyName, IDWriteFontCollection *sFontCollection, DWRITE_FONT_WEIGHT eWeight, DWRITE_FONT_STYLE eStyle, DWRITE_FONT_STRETCH eStretchStyle, FLOAT fSize, WCHAR const *wstrLocaleName, IDWriteTextFormat **ptrpTextFormat);
_WR_EXTERN_C_ ULONG   WINAPI WrDWrite_Factory_Release(IDWriteFactory *sFactory);

_WR_EXTERN_C_ ULONG WINAPI WrDWrite_TextFormat_Release(IDWriteTextFormat *sTextFormat);


